[package]
name = "herbig-haro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.30"
enquirer = "0.6.1"
execute = "0.2.11"
